language: node_js
node_js:
  - "8"
  - "6"
  - "5"
  - "4"
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++


install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run build
